### ISSUE TITLE
Just wanted to communicate

### ISSUE THREAD

**Issue by skillzaa** [QuinsZouls/lit-tailwindcss#1]
I could not find any other way to communicate with you on Git hub thus I created this ticket. Hope it is ok. 
All I wanted to say was that this is exactly what I was looking for, do you intend to continue working on this???? 
Thanks

**Comment by QuinsZouls** [comment]
Hi, I plan to update it to improve performance in future versions (that includes updating the tailwind version).
Issues are open in case you need to update the version of tailwind
